version: "3.7"
services:
  postgres:
    image: postgres:14.2
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      .env
    command: "migrate:up"
    depends_on:
      - postgres
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data: